version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install -y gnupg1 gnupg2

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: make

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: make test
